package wa.LibraUtil;

public class JsUtil {

	//cssカット
	static String css_cut() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("var d = document;");
		jsc.append("var delarr = new Array();");
		jsc.append("var links = d.getElementsByTagName(\"link\");");
		jsc.append("for(var i=0; i<links.length; i++) {");
		jsc.append("var link = links.item(i);");
		jsc.append("var href = link.getAttribute(\"href\");");
		jsc.append("if(is_css_file(href) || is_css_link(link)) {");
		jsc.append("delarr.push(href);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var i=0; i<delarr.length; i++) {");
		jsc.append("var line = delarr[i];");
		jsc.append("delete_link(line);");
		jsc.append("}");
		jsc.append("var tags = d.getElementsByTagName(\"*\");");
		jsc.append("for(var i=0; i<tags.length; i++) {");
		jsc.append("var tag = tags.item(i);");
		jsc.append("var style = tag.getAttribute(\"style\");");
		jsc.append("if(style !== null || style !== \"\") {");
		jsc.append("tag.removeAttribute(\"style\");");
		jsc.append("}");
		jsc.append("}");
		jsc.append("var styles = d.getElementsByTagName(\"style\");");
		jsc.append("for(i=0; i<styles.length; i++) {");
		jsc.append("var style = styles.item(i);");
		jsc.append("style.textContent = null;");
		jsc.append("}");
		jsc.append("function is_css_file(href) {");
		jsc.append("var pat = new RegExp(\".+\\.css\");");
		jsc.append("if(pat.test(href)) return true;");
		jsc.append("else return false;");
		jsc.append("}");
		jsc.append("function is_css_link(link) {");
		jsc.append("if(link.hasAttribute(\"type\")) {");
		jsc.append("var pat = new RegExp(\"text/css\");");
		jsc.append("var type = link.getAttribute(\"type\");");
		jsc.append("if(pat.test(type)) return true;");
		jsc.append("else return false;");
		jsc.append("} else {");
		jsc.append("return false;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function delete_link(line) {");
		jsc.append("var lks = d.getElementsByTagName(\"link\");");
		jsc.append("for(var j=0; j<lks.length; j++) {");
		jsc.append("var lk = lks.item(j);");
		jsc.append("var hf = lk.getAttribute(\"href\");");
		jsc.append("if(hf === line) {");
		jsc.append("lk.parentNode.removeChild(lk);");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		return jsc.toString();
	}

	//alt属性値を表示
	static String image_alt() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("var fname_flg = true;");
		jsc.append("var img = document.getElementsByTagName(\"img\");");
		jsc.append("for(var i=0; i<img.length; i++) {");
		jsc.append("var imgtag = img.item(i);");
		jsc.append("imgtag.setAttribute(\"style\", \"border:1px solid red;\");");
		jsc.append("var span_id = \"bkm-img-span-\" + i;");
		jsc.append("var src_val = imgtag.getAttribute(\"src\");");
		jsc.append("var fname = get_img_filename(src_val);");
		jsc.append("var alt_val = imgtag.getAttribute(\"alt\");");
		jsc.append("if(alt_val === null) {");
		jsc.append("alt_val = alt_attr_from_dirtycode(imgtag);");
		jsc.append("}");
		jsc.append("var html_str = \"\";");
		jsc.append("if(alt_attr_check(imgtag)) {");
		jsc.append("html_str += \"alt: \" + alt_val;");
		jsc.append("} else {");
		jsc.append("html_str += \"alt属性がない\";");
		jsc.append("}");
		jsc.append("if(fname_flg) {");
		jsc.append("if(html_str !== \"\") {");
		jsc.append("html_str += \", filename: \" + fname;");
		jsc.append("} else {");
		jsc.append("html_str += \"filename: \" + fname;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("var css_txt = \"color:#fff;font-size:12px;padding:1px;background:#BF0000;\";");
		jsc.append("var span = '<span id=\"' + span_id + '\" style=\"' + css_txt + '\">' + html_str + '</span>';");
		jsc.append("imgtag.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("tag_link_img();");
		jsc.append("function alt_attr_from_dirtycode(obj) {");
		jsc.append("var ret = \"\";");
		jsc.append("var imgtag = obj.outerHTML;");
		jsc.append("var pt = new RegExp('(alt=\")(.*?)(\")');");
		jsc.append("if(pt.test(imgtag)) {");
		jsc.append("ret = imgtag.match(pt)[2];");
		jsc.append("}");
		jsc.append("return ret;");
		jsc.append("}");
		jsc.append("function get_img_filename(str) {");
		jsc.append("var ret = \"\";");
		jsc.append("var pat = new RegExp(\"(.+)\\/(.+\\.)(JPG|jpg|GIF|gif|PNG|png|BMP|bmp)$\");");
		jsc.append("if(pat.test(str)) {");
		jsc.append("var arr = str.match(pat);");
		jsc.append("ret += arr[2] + arr[3];");
		jsc.append("}");
		jsc.append("return ret;");
		jsc.append("}");
		jsc.append("function alt_attr_check(imgtag) {");
		jsc.append("var txt = imgtag.outerHTML;");
		jsc.append("var pt1 = new RegExp('alt=\".*\"');");
		jsc.append("var pt2 = new RegExp('alt=');");
		jsc.append("if(pt1.test(txt) && pt2.test(txt)) return true;");
		jsc.append("else return false;");
		jsc.append("}");
		jsc.append("function tag_link_img() {");
		jsc.append("var ats = document.getElementsByTagName(\"a\");");
		jsc.append("var css_txt = \"border:2px dotted red;\";");
		jsc.append("for(var i=0; i<ats.length; i++) {");
		jsc.append("var atag = ats.item(i);");
		jsc.append("var imgs = atag.getElementsByTagName(\"img\");");
		jsc.append("for(var j=0; j<imgs.length; j++) {");
		jsc.append("var img = imgs.item(j);");
		jsc.append("img.setAttribute(\"style\", css_txt);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		return jsc.toString();
	}
	
	//target属性値を表示
	static String target_attr() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("var ats = document.getElementsByTagName(\"a\");");
		jsc.append("for(var i=0; i<ats.length; i++) {");
		jsc.append("var atag = ats.item(i);");
		jsc.append("var ataghtml = atag.outerHTML;");
		jsc.append("ataghtml = _text_clean(ataghtml);");
		jsc.append("if(_target_attr_check(ataghtml)) {");
		jsc.append("var target_vl = atag.getAttribute(\"target\");");
		jsc.append("var span_id = \"bkm-target-attr-span-\" + i;");
		jsc.append("var span_html = (target_vl === \"\") ? \"target属性有:(空)\" : \"target属性有:\" + target_vl;");
		jsc.append("var span_css = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
		jsc.append("var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
		jsc.append("atag.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function _target_attr_check(str) {");
		jsc.append("var pt = new RegExp('target=\".*?\"');");
		jsc.append("if(pt.test(str)) return true;");
		jsc.append("else return false;");
		jsc.append("}");
		jsc.append("function _text_clean(str) {");
		jsc.append("var ret = \"\";");
		jsc.append("ret = str.replace(new RegExp(\"^ +\", \"mg\"), \"\");");
		jsc.append("ret = ret.replace(new RegExp(\"\\t+\", \"mg\"), \"\");");
		jsc.append("ret = ret.replace(new RegExp(\"(\\r\\n|\\r|\\n)\", \"mg\"), \"\");");
		jsc.append("return str;");
		jsc.append("}");
		return jsc.toString();
	}
	
	//semantic要素を表示
	static String semantic_check() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("function tag_paragraph() {");
		jsc.append("var ps = document.getElementsByTagName(\"p\");");
		jsc.append("for(var i=0; i<ps.length; i++) {");
		jsc.append("var p = ps.item(i);");
		jsc.append("p.setAttribute(\"style\", \"border:1px solid #3A87AD; position: relative;\");");
		jsc.append("add_label(p, i, \"afterbegin\", \"#3A87AD\");");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_heading() {");
		jsc.append("var tags = [\"h1\", \"h2\", \"h3\", \"h4\", \"h5\", \"h6\"];");
		jsc.append("var idx = tags.length;");
		jsc.append("var in_funcs = new Array();");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("var val = tags[i];");
		jsc.append("in_funcs.push(make_funcs(val));");
		jsc.append("}");
		jsc.append("function make_funcs(tag) {");
		jsc.append("return function() {");
		jsc.append("var ts = document.getElementsByTagName(tag);");
		jsc.append("for(var i=0; i<ts.length; i++) {");
		jsc.append("var t = ts.item(i);");
		jsc.append("t.setAttribute(\"style\", \"border:1px solid red; position: relative;\");");
		jsc.append("add_label(t, i, \"afterbegin\", \"#B94A48\");");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("in_funcs[i]();");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_br() {");
		jsc.append("var brs = document.getElementsByTagName(\"br\");");
		jsc.append("for(var i=0; i<brs.length; i++) {");
		jsc.append("var br = brs.item(i);");
		jsc.append("var css_txt = \"color:#fff;font-size:90%!important;padding:1px;border-radius:3px;\";");
		jsc.append("var span = '<span id=\"bkm-br-span-' + i + '\" style=\"' + css_txt + 'background:#888888;\">&lt;br&gt;</span>';");
		jsc.append("br.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_semantic() {");
		jsc.append("var tags = [\"strong\", \"em\", \"address\", \"nav\", \"section\"];");
		jsc.append("var idx = tags.length;");
		jsc.append("var in_funcs = new Array();");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("var val = tags[i];");
		jsc.append("in_funcs.push(make_funcs(val));");
		jsc.append("}");
		jsc.append("function make_funcs(tag) {");
		jsc.append("return function() {");
		jsc.append("var ts = document.getElementsByTagName(tag);");
		jsc.append("for(var i=0; i<ts.length; i++) {");
		jsc.append("var t = ts.item(i);");
		jsc.append("t.setAttribute(\"style\", \"border:1px solid #808080; position: relative;\");");
		jsc.append("add_label(t, i, \"afterbegin\", \"#888888\");");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("in_funcs[i]();");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_list() {");
		jsc.append("var tags = [\"ul\", \"ol\", \"dl\", \"dt\", \"dd\"];");
		jsc.append("var idx = tags.length;");
		jsc.append("var in_funcs = new Array();");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("var val = tags[i];");
		jsc.append("in_funcs.push(make_funcs(val));");
		jsc.append("}");
		jsc.append("function make_funcs(tag) {");
		jsc.append("return function() {");
		jsc.append("var ts = document.getElementsByTagName(tag);");
		jsc.append("for(var i=0; i<ts.length; i++) {");
		jsc.append("var t = ts.item(i);");
		jsc.append("t.setAttribute(\"style\", \"border:1px solid #468847; position: relative;\");");
		jsc.append("add_label(t, i, \"afterbegin\", \"#468847\");");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("in_funcs[i]();");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_table() {");
		jsc.append("var in_funcs = [");
		jsc.append("function() {");
		jsc.append("var tbls = document.getElementsByTagName(\"table\");");
		jsc.append("for(var i=0; i<tbls.length; i++) {");
		jsc.append("var tbl = tbls.item(i);");
		jsc.append("tbl.setAttribute(\"style\", \"border:2px solid red!important; position: relative;\");");
		jsc.append("add_label(tbl, i, \"beforebegin\", \"#800000\");");
		jsc.append("}");
		jsc.append("for(var i=0; i<tbls.length; i++) {");
		jsc.append("var tbl = tbls.item(i);");
		jsc.append("var smry = tbl.getAttribute(\"summary\");");
		jsc.append("var span = document.getElementById(\"bkm-table-span-\" + i);");
		jsc.append("var now_label_text = span.innerHTML;");
		jsc.append("var new_label_text = (smry === null) ? now_label_text : now_label_text + \", summary:\" + smry;");
		jsc.append("span.innerHTML = new_label_text;");
		jsc.append("}");
		jsc.append("},");
		jsc.append("function() {");
		jsc.append("var cps = document.getElementsByTagName(\"caption\");");
		jsc.append("for(var i=0; i<cps.length; i++) {");
		jsc.append("var cp = cps.item(i);");
		jsc.append("cp.setAttribute(\"style\", \"border:1px solid red!important; position: relative;\");");
		jsc.append("add_label(cp, i, \"afterbegin\", \"#800000\");");
		jsc.append("}");
		jsc.append("},");
		jsc.append("function() {");
		jsc.append("var ths = document.getElementsByTagName(\"th\");");
		jsc.append("for(var i=0; i<ths.length; i++) {");
		jsc.append("var th = ths.item(i);");
		jsc.append("th.setAttribute(\"style\", \"border:2px solid red!important; position: relative;\");");
		jsc.append("add_label(th, i, \"afterbegin\", \"#800000\");");
		jsc.append("}");
		jsc.append("for(var i=0; i<ths.length; i++) {");
		jsc.append("var th = ths.item(i);");
		jsc.append("var scope = th.getAttribute(\"scope\");");
		jsc.append("var span = document.getElementById(\"bkm-th-span-\" + i);");
		jsc.append("var now_label_text = span.innerHTML;");
		jsc.append("var new_label_text = (scope===null) ? now_label_text : now_label_text + \", scope:\" + scope;");
		jsc.append("span.innerHTML = new_label_text;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("];");
		jsc.append("for(var i=0; i<in_funcs.length; i++) {");
		jsc.append("in_funcs[i]();");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_empty_a() {");
		jsc.append("var empas = document.querySelectorAll(\"a:empty, a span:empty\");");
		jsc.append("var i = 0;");
		jsc.append("for(itm of empas) {");
		jsc.append("var href_flg = null;");
		jsc.append("if(!itm.hasAttribute(\"name\")) {");
		jsc.append("var css_txt = \"color:#fff;font-size:90%!important;padding:1px;border-radius:3px;\";");
		jsc.append("var span = '<span id=\"bkm-empry-a-span-' + i + '\" style=\"' + css_txt + 'background:#C000C0;\">空リンク有</span>';");
		jsc.append("itm.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("i++;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function add_label(obj, cnt, pos, colorcode) {");
		jsc.append("var tag_name = obj.tagName;");
		jsc.append("tag_name = tag_name.toLowerCase();");
		jsc.append("var span_id = \"bkm-\" + tag_name + \"-span-\" + cnt;");
		jsc.append("var css_txt = \"color:#fff;font-size:90%!important;font-weight:normal!important;padding:1px;border-radius:3px;\";");
		jsc.append("css_txt += 'background:' + colorcode + ';';");
		jsc.append("var html_str = '&lt;' + tag_name + '&gt;';");
		jsc.append("var span = '<span id=\"' + span_id + '\" style=\"' + css_txt + '\">' + html_str + '</span>';");
		jsc.append("obj.insertAdjacentHTML(pos, span);");
		jsc.append("}");
		jsc.append("tag_paragraph();");
		jsc.append("tag_heading();");
		jsc.append("tag_br();");
		jsc.append("tag_semantic();");
		jsc.append("tag_list();");
		jsc.append("tag_table();");
		jsc.append("tag_empty_a();");
		return jsc.toString();
	}
	
	//lang属性値を表示
	static String lang_attr() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("var alltags = document.getElementsByTagName(\"*\");");
		jsc.append("var type = \"\";");
		jsc.append("for(var i=0; i<alltags.length; i++) {");
		jsc.append("var tag = alltags.item(i);");
		jsc.append("var tag_name = tag.tagName.toLowerCase();");
		jsc.append("if(tag.hasAttribute(\"lang\") || tag.hasAttribute(\"xml:lang\")) {");
		jsc.append("if(tag.hasAttribute(\"lang\") && tag.hasAttribute(\"xml:lang\")) {");
		jsc.append("type = \"all\";");
		jsc.append("} else if(tag.hasAttribute(\"lang\") && !tag.hasAttribute(\"xml:lang\")) {");
		jsc.append("type = \"lang-only\";");
		jsc.append("} else if(!tag.hasAttribute(\"lang\") && tag.hasAttribute(\"xml:lang\")) {");
		jsc.append("type = \"xml-lang-only\";");
		jsc.append("}");
		jsc.append("var lang_vl = \"\";");
		jsc.append("var xml_lang_vl = \"\";");
		jsc.append("if(type === \"all\") {");
		jsc.append("lang_vl = tag.getAttribute(\"lang\");");
		jsc.append("xml_lang_vl = tag.getAttribute(\"xml:lang\");");
		jsc.append("} else if(type === \"lang-only\") {");
		jsc.append("lang_vl = tag.getAttribute(\"lang\");");
		jsc.append("} else if(type === \"xml-lang-only\") {");
		jsc.append("xml_lang_vl = tag.getAttribute(\"xml:lang\");");
		jsc.append("}");
		jsc.append("var span_id = \"bkm-lang-attr-span-\" + i;");
		jsc.append("var span_html = \"\";");
		jsc.append("if(type === \"all\") {");
		jsc.append("span_html = (lang_vl === \"\") ? \"lang属性有:(空)\" : \"lang属性有: \" + lang_vl;");
		jsc.append("span_html += (xml_lang_vl === \"\") ? \" , xml:lang属性有:(空)\" : \" , xml:lang属性有: \" + xml_lang_vl;");
		jsc.append("} else if(type === \"lang-only\") {");
		jsc.append("span_html = (lang_vl === \"\") ? \"lang属性有:(空)\" : \"lang属性有: \" + lang_vl;");
		jsc.append("} else if(type === \"xml-lang-only\") {");
		jsc.append("span_html = (xml_lang_vl === \"\") ? \"xml:lang属性有:(空)\" : \"xml:lang属性有: \" + xml_lang_vl;");
		jsc.append("}");
		jsc.append("span_html = '&lt;' + tag.tagName.toLowerCase() + '&gt;要素 , ' + span_html;");
		jsc.append("var span_css = \"padding-right:5px;color:#fff;font-size:13px;padding:1px;background:#008000;border-radius:5px;\";");
		jsc.append("var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
		jsc.append("if(tag_name === \"img\") {");
		jsc.append("tag.insertAdjacentHTML(\"afterend\", span);");
		jsc.append("} else {");
		jsc.append("tag.insertAdjacentHTML(\"afterbegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		return jsc.toString();
	}
	
	//label要素とtitle属性値を表示
	static String tag_label_and_title_attr() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("function tag_label_label() {");
		jsc.append("var lbs = document.getElementsByTagName(\"label\");");
		jsc.append("for(var i=0; i<lbs.length; i++) {");
		jsc.append("var lb = lbs.item(i);");
		jsc.append("lb.setAttribute(\"style\", \"border:1px solid #468847!important; position: relative;\");");
		jsc.append("var span_html = \"\";");
		jsc.append("var span_style = \"\";");
		jsc.append("var span_id = \"bkm-label-span-\" + i;");
		jsc.append("var type = \"\";");
		jsc.append("if(lb.hasAttribute(\"for\")) {");
		jsc.append("type = \"for-is-yes\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
		jsc.append("} else {");
		jsc.append("type = \"for-is-no\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
		jsc.append("}");
		jsc.append("if(type === \"for-is-yes\") {");
		jsc.append("var for_vl = lb.getAttribute(\"for\");");
		jsc.append("span_html = (for_vl === \"\") ? \"for属性有:(空)\" : \"for属性有: \" + for_vl;");
		jsc.append("span_html = '&lt;' + lb.tagName.toLowerCase() + '&gt; , ' + span_html;");
		jsc.append("} else if(type === \"for-is-no\") {");
		jsc.append("span_html = '&lt;' + lb.tagName.toLowerCase() + '&gt; , for属性なし';");
		jsc.append("}");
		jsc.append("var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
		jsc.append("lb.insertAdjacentHTML(\"afterbegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_label_input() {");
		jsc.append("var ips = document.getElementsByTagName(\"input\");");
		jsc.append("for(var i=0; i<ips.length; i++) {");
		jsc.append("var ip = ips.item(i);");
		jsc.append("var typeattr = \"\";");
		jsc.append("if(!ip.hasAttribute(\"type\")) {");
		jsc.append("typeattr = \"text\";");
		jsc.append("} else {");
		jsc.append("typeattr = ip.getAttribute(\"type\");");
		jsc.append("}");
		jsc.append("if(typeattr === \"text\" || typeattr === \"radio\" || typeattr === \"checkbox\" || typeattr === \"password\") {");
		jsc.append("var span_html = \"\";");
		jsc.append("var span_style = \"\";");
		jsc.append("var span_id = \"bkm-input-span-\" + i;");
		jsc.append("ip.setAttribute(\"style\", \"border:1px solid blue; position: relative;\");");
		jsc.append("var type = \"\";");
		jsc.append("if(ip.hasAttribute(\"id\")) {");
		jsc.append("type = \"id-yes\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#3A87AD;border-radius:5px;\";");
		jsc.append("} else {");
		jsc.append("type = \"id-no\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
		jsc.append("}");
		jsc.append("if(type === \"id-yes\") {");
		jsc.append("var id_vl = ip.getAttribute(\"id\");");
		jsc.append("span_html = (id_vl === \"\") ? \"id属性有:(空)\" : \"id属性有: \" + id_vl;");
		jsc.append("} else if(type === \"id-no\") {");
		jsc.append("span_html = \"id属性なし\";");
		jsc.append("}");
		jsc.append("var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
		jsc.append("ip.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_label_textarea() {");
		jsc.append("var tas = document.getElementsByTagName(\"textarea\");");
		jsc.append("for(var i=0; i<tas.length; i++) {");
		jsc.append("var ta = tas.item(i);");
		jsc.append("ta.setAttribute(\"style\", \"border:1px solid blue; position: relative;\");");
		jsc.append("var span_html = \"\";");
		jsc.append("var span_style = \"\";");
		jsc.append("var span_id = \"bkm-textarea-span-\" + i;");
		jsc.append("var type = \"\";");
		jsc.append("if(ta.hasAttribute(\"id\")) {");
		jsc.append("type = \"id-yes\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#3A87AD;border-radius:5px;\";");
		jsc.append("} else {");
		jsc.append("type = \"id-no\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
		jsc.append("}");
		jsc.append("if(type === \"id-yes\") {");
		jsc.append("var id_vl = ta.getAttribute(\"id\");");
		jsc.append("span_html = (id_vl === \"\") ? \"id属性有:(空)\" : \"id属性有: \" + id_vl;");
		jsc.append("} else if(type === \"id-no\") {");
		jsc.append("span_html = \"id属性なし\";");
		jsc.append("}");
		jsc.append("var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
		jsc.append("ta.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_label_select() {");
		jsc.append("var sls = document.getElementsByTagName(\"select\");");
		jsc.append("for(var i=0; i<sls.length; i++) {");
		jsc.append("var sl = sls.item(i);");
		jsc.append("sl.setAttribute(\"style\", \"border:1px solid blue; position: relative;\");");
		jsc.append("var span_html = \"\";");
		jsc.append("var span_style = \"\";");
		jsc.append("var span_id = \"bkm-select-span-\" + i;");
		jsc.append("var type = \"\";");
		jsc.append("if(sl.hasAttribute(\"id\")) {");
		jsc.append("type = \"id-yes\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#3A87AD;border-radius:5px;\";");
		jsc.append("} else {");
		jsc.append("type = \"id-no\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
		jsc.append("}");
		jsc.append("if(type === \"id-yes\") {");
		jsc.append("var id_vl = sl.getAttribute(\"id\");");
		jsc.append("span_html = (id_vl === \"\") ? \"id属性有:(空)\" : \"id属性有: \" + id_vl;");
		jsc.append("} else if(type === \"id-no\") {");
		jsc.append("span_html = \"id属性なし\";");
		jsc.append("}");
		jsc.append("var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
		jsc.append("sl.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function tag_title_attr() {");
		jsc.append("var tags = [\"a\", \"input\", \"textarea\", \"select\"];");
		jsc.append("var idx = tags.length;");
		jsc.append("var in_funcs = new Array();");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("var val = tags[i];");
		jsc.append("in_funcs.push(make_funcs(val));");
		jsc.append("}");
		jsc.append("function make_funcs(tag) {");
		jsc.append("return function() {");
		jsc.append("var ts = document.getElementsByTagName(tag);");
		jsc.append("for(var i=0; i<ts.length; i++) {");
		jsc.append("var t = ts.item(i);");
		jsc.append("var typeattr = \"\";");
		jsc.append("var tag_name = t.tagName.toLowerCase();");
		jsc.append("if(tag_name === \"input\") {");
		jsc.append("if(!t.hasAttribute(\"type\")) {");
		jsc.append("typeattr = \"text\";");
		jsc.append("} else {");
		jsc.append("typeattr = t.getAttribute(\"type\");");
		jsc.append("}");
		jsc.append("if(typeattr === \"text\" || typeattr === \"radio\" || typeattr === \"checkbox\") {");
		jsc.append("var span_html = \"\";");
		jsc.append("var span_style = \"\";");
		jsc.append("var span_id = \"bkm-title-attr-span-\" + i;");
		jsc.append("var type = \"\";");
		jsc.append("if(t.hasAttribute(\"title\")) {");
		jsc.append("type = \"title-yes\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
		jsc.append("} else {");
		jsc.append("type = \"title-no\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
		jsc.append("}");
		jsc.append("if(type === \"title-yes\") {");
		jsc.append("var title_vl = t.getAttribute(\"title\");");
		jsc.append("span_html = (title_vl === \"\") ? \"title属性有:(空)\" : \"title属性有: \" + title_vl;");
		jsc.append("} else if(type === \"title-no\") {");
		jsc.append("span_html = \"title属性なし\";");
		jsc.append("}");
		jsc.append("var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
		jsc.append("t.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("} else if(tag_name === \"textarea\" || tag_name === \"select\") {");
		jsc.append("var span_html = \"\";");
		jsc.append("var span_style = \"\";");
		jsc.append("var span_id = \"bkm-title-attr-span-\" + i;");
		jsc.append("var type = \"\";");
		jsc.append("if(t.hasAttribute(\"title\")) {");
		jsc.append("type = \"title-yes\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
		jsc.append("} else {");
		jsc.append("type = \"title-no\";");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
		jsc.append("}");
		jsc.append("if(type === \"title-yes\") {");
		jsc.append("var title_vl = t.getAttribute(\"title\");");
		jsc.append("span_html = (title_vl === \"\") ? \"title属性有:(空)\" : \"title属性有: \" + title_vl;");
		jsc.append("} else if(type === \"title-no\") {");
		jsc.append("span_html = \"title属性なし\";");
		jsc.append("}");
		jsc.append("var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
		jsc.append("t.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("} else {");
		jsc.append("var span_html = \"\";");
		jsc.append("var span_style = \"\";");
		jsc.append("var span_id = \"bkm-title-attr-span-\" + i;");
		jsc.append("if(t.hasAttribute(\"title\")) {");
		jsc.append("var title_vl = t.getAttribute(\"title\");");
		jsc.append("span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
		jsc.append("span_html = (title_vl === \"\") ? \"title属性有:(空)\" : \"title属性有: \" + title_vl;");
		jsc.append("var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
		jsc.append("t.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var i=0; i<idx; i++) {");
		jsc.append("in_funcs[i]();");
		jsc.append("}");
		jsc.append("}");
		jsc.append("tag_label_label();");
		jsc.append("tag_label_input();");
		jsc.append("tag_label_textarea();");
		jsc.append("tag_label_select();");
		jsc.append("tag_title_attr();");
		return jsc.toString();
	}
	
	//文書リンクを表示
	static String document_link() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("var regx_arr = new Array();");
		jsc.append("var exts = [\"pdf\", \"doc\", \"docx\", \"xls\", \"xlsx\", \"jtd\", \"ppt\", \"pptx\", \"csv\", \"odt\", \"ods\", \"odp\", \"zip\"];");
		jsc.append("for(var i=0; i<exts.length; i++) {");
		jsc.append("var ext = exts[i];");
		jsc.append("var in_regx = new RegExp(\"(.*\\/*)(.+\\.)(\" + ext + \")$\");");
		jsc.append("regx_arr.push(in_regx);");
		jsc.append("}");
		jsc.append("var ats = document.getElementsByTagName(\"a\");");
		jsc.append("for(var i=0; i<ats.length; i++) {");
		jsc.append("var atag = ats.item(i);");
		jsc.append("if(atag.hasAttribute(\"href\")) {");
		jsc.append("href_vl = atag.getAttribute(\"href\");");
		jsc.append("if(is_doc_link(regx_arr, href_vl)) {");
		jsc.append("var cr_ext = get_document_type(regx_arr, href_vl);");
		jsc.append("var span_id = \"bkm-isdocument-span-\" + i;");
		jsc.append("var span_html = \"Fileリンク: \" + cr_ext;");
		jsc.append("var span_css = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C000C0;border-radius:5px;\";");
		jsc.append("var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
		jsc.append("atag.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("} else if(is_premium_pdf_link(href_vl)) {");
		jsc.append("var span_id = \"bkm-isdocument-span-\" + i;");
		jsc.append("var span_html = \"Fileリンクの可能性有: PDF\";");
		jsc.append("var span_css = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C000C0;border-radius:5px;\";");
		jsc.append("var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
		jsc.append("atag.insertAdjacentHTML(\"beforebegin\", span);");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("function is_premium_pdf_link(str) {");
		jsc.append("str = str.toLowerCase();");
		jsc.append("var pt = new RegExp(/(\\.pdf#|\\.pdf\\?)/);");
		jsc.append("if(pt.test(str)) return true;");
		jsc.append("else return false;");
		jsc.append("}");
		jsc.append("function is_doc_link(arr, str) {");
		jsc.append("var flag = false;");
		jsc.append("for(var i=0; i<arr.length; i++) {");
		jsc.append("var aval = arr[i];");
		jsc.append("if(aval.test(str)) {");
		jsc.append("flag = true;");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("return flag;");
		jsc.append("}");
		jsc.append("function get_document_type(arr, str) {");
		jsc.append("var ret = \"\";");
		jsc.append("for(var i=0; i<arr.length; i++) {");
		jsc.append("var aval = arr[i];");
		jsc.append("if(aval.test(str)) {");
		jsc.append("ret = str.match(aval)[3];");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("ret = ret.toUpperCase();");
		jsc.append("return ret;");
		jsc.append("}");
		return jsc.toString();
	}
	
	//対象ソースコード一覧を取得する(検査メインページから)
	public static String get_srccode_list() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("var src = document.getElementById(\"source\");");
		jsc.append("var dch = src.childNodes;");
		jsc.append("var str = \"\";");
		jsc.append("for(var i=0; i<dch.length; i++){");
		jsc.append("if(dch.item(i).id){");
		jsc.append("var j = i + 1;");
		jsc.append("if(dch.item(j).nodeValue != null){");
		jsc.append("str += dch.item(j).nodeValue + \"<bkmk:br>\";");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("return str;");
		return jsc.toString();
	}
	
	//対象ソースコード一覧を取得する(一括検査画面から)
	public static String get_srccode_list_from_all_sv() {
		StringBuilder jsc = new StringBuilder();
		jsc.append("class allSurveyByTable {");
		jsc.append("constructor() {");
		jsc.append("this.sp = \"<bkmk:br>\";");
		jsc.append("this.heading = document.getElementsByTagName(\"table\").item(0);");
		jsc.append("this.tbl = document.getElementsByTagName(\"table\").item(2);");
		jsc.append("this.hash = {");
		jsc.append("\"UNCOMP\": \"未判定\",");
		jsc.append("\"PASS\":\"適合\",");
		jsc.append("\"PASS2\":\"適合(注記)\",");
		jsc.append("\"FAIL\":\"不適合\",");
		jsc.append("\"NA\":\"非適用\"");
		jsc.append("};");
		jsc.append("this.flags = {");
		jsc.append("\"UNCOMP\": \"CHECK\",");
		jsc.append("\"PASS\": \"PASS_HC\",");
		jsc.append("\"PASS2\": \"PASS2\",");
		jsc.append("\"FAIL\": \"FAIL_HC\",");
		jsc.append("\"NA\": \"NA_HC\"");
		jsc.append("};");
		jsc.append("this.nmflags = {");
		jsc.append("\"CHECK\": \"0\",");
		jsc.append("\"PASS_HC\": \"1\",");
		jsc.append("\"PASS2\": \"2\",");
		jsc.append("\"FAIL_HC\": \"3\",");
		jsc.append("\"NA_HC\": \"4\"");
		jsc.append("};");
		jsc.append("}");
		jsc.append("init_datas() {");
		jsc.append("return this.tbl.rows;");
		jsc.append("}");
		jsc.append("survey_obj(row_obj) {");
		jsc.append("return row_obj.cells.item(2);");
		jsc.append("}");
		jsc.append("comment_obj(row_obj) {");
		jsc.append("return row_obj.cells.item(3);");
		jsc.append("}");
		jsc.append("description_obj(row_obj) {");
		jsc.append("return row_obj.cells.item(4);");
		jsc.append("}");
		jsc.append("srccode_obj(row_obj) {");
		jsc.append("return row_obj.cells.item(5);");
		jsc.append("}");
		jsc.append("get_text(obj) {");
		jsc.append("return obj.getElementsByTagName(\"textarea\").item(0).value;");
		jsc.append("}");
		jsc.append("set_text(obj, str) {");
		jsc.append("obj.getElementsByTagName(\"textarea\").item(0).value = str;");
		jsc.append("}");
		jsc.append("clear_text(obj) {");
		jsc.append("obj.getElementsByTagName(\"textarea\").item(0).value = \"\";");
		jsc.append("}");
		jsc.append("set_survey(obj, flag) {");
		jsc.append("var ts = obj.getElementsByTagName(\"select\").item(0);");
		jsc.append("var flag_key = \"\";");
		jsc.append("for(var key in this.hash) {");
		jsc.append("var vl = this.hash[key];");
		jsc.append("if(vl == flag) {");
		jsc.append("flag_key = key;");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("var key_val = \"\";");
		jsc.append("for(var key in this.flags) {");
		jsc.append("if(key == flag_key) {");
		jsc.append("key_val = this.flags[key];");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("var key_nm = 0;");
		jsc.append("for(var key in this.nmflags) {");
		jsc.append("if(key == key_val) {");
		jsc.append("key_nm = Number(this.nmflags[key]);");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var i=0; i<ts.length; i++) {");
		jsc.append("if(ts.options[i].value == key_val) {");
		jsc.append("ts.selectedIndex = key_nm;");
		jsc.append("var event = document.createEvent(\"HTMLEvents\");");
		jsc.append("event.initEvent(\"change\", true, false);");
		jsc.append("ts.dispatchEvent(event);");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("get_survey(obj) {");
		jsc.append("var ts = obj.getElementsByTagName(\"select\").item(0);");
		jsc.append("var idx = ts.selectedIndex + \"\";");
		jsc.append("var primary_key = \"\";");
		jsc.append("var secondary_key = \"\";");
		jsc.append("var hash_val = \"\";");
		jsc.append("for(var key in this.nmflags) {");
		jsc.append("var val = this.nmflags[key] + \"\";");
		jsc.append("if(idx === val) {");
		jsc.append("primary_key = key;");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var key in this.flags) {");
		jsc.append("var val = this.flags[key];");
		jsc.append("if(primary_key === val) {");
		jsc.append("secondary_key = key;");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("for(var key in this.hash) {");
		jsc.append("if(key == secondary_key) {");
		jsc.append("hash_val = this.hash[key];");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("return hash_val;");
		jsc.append("}");
		jsc.append("is_text_empty(obj) {");
		jsc.append("var ta = obj.getElementsByTagName(\"textarea\").item(0);");
		jsc.append("if(ta.value === \"\" || ta.value === null) return true;");
		jsc.append("else return false;");
		jsc.append("}");
		jsc.append("save() {");
		jsc.append("var d = document.getElementsByTagName(\"input\");");
		jsc.append("for(var i=0; i < d.length; i++) {");
		jsc.append("var itag = d.item(i);");
		jsc.append("var ival = itag.value;");
		jsc.append("if(ival == \"一括登録\") {");
		jsc.append("itag.click();");
		jsc.append("break;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("}");
		jsc.append("clean_text(str) {");
		jsc.append("str = str.replace(/^ +/mg, \"\");");
		jsc.append("str = str.replace(/(\\r\\n|\\n)/mg, \"\");");
		jsc.append("str = str.replace(/\\t/mg, \"\");");
		jsc.append("return str;");
		jsc.append("}");
		jsc.append("get_tech_code() {");
		jsc.append("var rows = this.heading.rows;");
		jsc.append("var row = rows.item(0);");
		jsc.append("return row.cells.item(5).innerText;");
		jsc.append("}");
		jsc.append("}");
		jsc.append("let app = new allSurveyByTable();");
		jsc.append("let arr = app.init_datas();");
		jsc.append("let str = \"\";");
		jsc.append("for(var i=0; i<arr.length; i++) {");
		jsc.append("if(i == 0) continue;");
		jsc.append("var row = arr.item(i);");
		jsc.append("var survey_obj = app.survey_obj(row);");
		jsc.append("var comment_obj = app.comment_obj(row);");
		jsc.append("var description_obj = app.description_obj(row);");
		jsc.append("var srccode_obj = app.srccode_obj(row);");
		jsc.append("var description = app.clean_text(app.get_text(description_obj));");
		jsc.append("if(description == \"\") str += \" \" + app.sp;");
		jsc.append("else str += description + app.sp;");
		jsc.append("}");
		jsc.append("return str;");
		return jsc.toString();
	}


}
